#!/usr/bin/env python3
"""
The operation brain: one indexed memory for everything this pipeline knows.

Why this exists: the knowledge that runs this operation is real but scattered.
Active rules live in workflow/incident-log.md, stage contracts in
workflow/pipeline.md, gate criteria across twenty checklists, topic strategy in
ROADMAP.md, brand law in brand/, and per-article truth in 36 blog folders. A
session (human or Claude) that needs to know "what did we decide about X" has
no entry point except reading everything. Knowledge that cannot be recalled on
demand is knowledge the next run re-learns the hard way, which is the exact
failure mode the incident log was created to stop.

The brain has two halves and this script owns both.

  1. Recall. `search` and `rules` retrieve across every markdown file in the
     repo with heading-aware chunking, so a question gets an answer with a
     file:line to verify it against.

  2. Index. `build` regenerates the derived registries under brain/ from their
     upstream sources (never the other way round), and `check` fails when the
     index has drifted from those sources. Anything hand-written under brain/
     is curated knowledge with no upstream; anything generated carries a
     banner and is rebuilt, never edited.

Extraction is deliberately borrowed, not reimplemented: BLOCKING patterns come
from check-rules.py and draft field parsing from make_paste_kit.py, the same
import-the-source pattern qa_battery.py uses, so the brain can never disagree
with the linter or the paste kit about what a rule says or what a draft holds.

Exit codes:
  0  ok
  1  findings (drift, broken reference, failed invariant)
  2  invocation error

Usage:
  python3 workflow/brain.py build                  # regenerate brain/ indexes
  python3 workflow/brain.py check                  # CI gate: index matches sources
  python3 workflow/brain.py search "drive delivery" # ranked recall
  python3 workflow/brain.py rules --category tooling
  python3 workflow/brain.py stats
"""
import argparse
import importlib.util
import json
import math
import re
import sys
from collections import Counter, defaultdict
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
WORKFLOW = REPO_ROOT / 'workflow'
BRAIN = REPO_ROOT / 'brain'
BLOG = REPO_ROOT / 'blog'
INCIDENT_LOG = WORKFLOW / 'incident-log.md'
ROADMAP = REPO_ROOT / 'ROADMAP.md'


def _load(name, path):
    spec = importlib.util.spec_from_file_location(name, path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


_cr = _load('check_rules', WORKFLOW / 'check-rules.py')
_mpk = _load('make_paste_kit', WORKFLOW / 'make_paste_kit.py')

# The linter's own BLOCKING list. Generated files mirror upstream prose, and
# upstream prose sometimes quotes a banned pattern under a pragma. Re-deriving
# the ban list here would let the two drift, so we import it.
BLOCKING_PATTERNS = [pattern for _, pattern, _ in _cr.BLOCKING]
ALLOW_PRAGMA = '<!-- check-rules: allow -->'

GENERATED_BANNER = (
    '<!-- GENERATED by `python3 workflow/brain.py build`. Do not hand-edit: '
    'edits are overwritten on the next build and CI fails on drift. -->'
)

# Enforcement markers. Any file may claim it enforces a rule by carrying
# `brain-rule: <rule-id>` in a comment. The registry reads those claims back so
# the brain knows which of its rules a machine checks and which ride on
# discipline alone.
MARKER = re.compile(r'brain-rule:\s*(R-[a-z0-9-]+)')
RULE_REF = re.compile(r'\bR-[a-z0-9-]{4,}\b')
DECISION_REF = re.compile(r'\bD-\d{3}\b')

SEARCH_SKIP_DIRS = {'.git', '.venv', 'node_modules', '__pycache__'}
CODE_SUFFIXES = {'.py', '.sh', '.yml', '.yaml', '.json', '.css', '.tsx'}


# ---------------------------------------------------------------------------
# helpers
# ---------------------------------------------------------------------------

def rel(path):
    """Repo-relative path string, for stable output across machines."""
    path = Path(path)
    try:
        return str(path.resolve().relative_to(REPO_ROOT))
    except ValueError:
        return str(path)


def slugify(text, max_len=44):
    """Stable id fragment from a human label."""
    text = re.sub(r'[^a-z0-9]+', '-', text.lower()).strip('-')
    if len(text) <= max_len:
        return text
    cut = text[:max_len]
    if '-' in cut:
        cut = cut.rsplit('-', 1)[0]
    return cut.strip('-')


def sanitize(line):
    """Carry the linter pragma onto a generated line that quotes a ban.

    Generated files sit inside the linted scope, and their content is lifted
    from sources where a banned pattern is quoted on purpose (the ban list
    itself, an incident that names the word it caught). Upstream carries a
    pragma on those lines; a mirror of the line has to carry it too, or the
    brain would fail the very rules it publishes.
    """
    if not line.strip() or ALLOW_PRAGMA in line:
        return line
    for pattern in BLOCKING_PATTERNS:
        if pattern.search(line):
            return line.rstrip() + '  ' + ALLOW_PRAGMA
    return line


def emit(lines):
    """Join generated lines, sanitizing each, with a trailing newline."""
    return '\n'.join(sanitize(ln) for ln in lines).rstrip('\n') + '\n'


def read(path):
    try:
        return Path(path).read_text(encoding='utf-8')
    except (OSError, UnicodeDecodeError):
        return ''


def first_heading(text, default=''):
    for line in text.split('\n'):
        if line.startswith('# '):
            return line[2:].strip()
    return default


def first_prose(text, limit=200):
    """First prose sentence of a document, for one-line index summaries.

    Paragraphs in this repo are hard-wrapped, so the first sentence is usually
    spread over two or three physical lines. Gather the paragraph first, then
    cut at the sentence.
    """
    body = re.sub(r'^---\n.*?\n---\n', '', text, flags=re.S)
    paragraph = []
    for line in body.split('\n'):
        stripped = line.strip()
        if not stripped or stripped.startswith(('#', '>', '|', '-', '*', '`', '<!--', '[![')):
            if paragraph:
                break
            continue
        paragraph.append(stripped)
    if not paragraph:
        return ''
    joined = ' '.join(paragraph)
    joined = re.sub(r'\*\*(.+?)\*\*', r'\1', joined)
    joined = re.sub(r'`(.+?)`', r'\1', joined)
    joined = re.sub(r'\[(.+?)\]\([^)]*\)', r'\1', joined)
    return re.split(r'(?<=[.!?])\s', joined)[0].strip()[:limit]


def cell(text, limit=None):
    """Make a string safe to drop into a markdown table cell."""
    text = ' '.join(str(text).split()).replace('|', '/')
    if limit and len(text) > limit:
        text = text[:limit - 1].rstrip() + '…'
    return text


# ---------------------------------------------------------------------------
# parsers: every fact in the brain is lifted from a file that already owns it
# ---------------------------------------------------------------------------

FIELD_BULLET = re.compile(r'^-\s+\*\*(.+?):?\*\*:?\s*(.*)$')
DATED_ENTRY = re.compile(r'^#{2,3}\s+(\d{4}-\d{2}-\d{2}):\s*(.+)$')
H2 = re.compile(r'^##\s+(.+)$')
H3 = re.compile(r'^###\s+(.+)$')


def parse_incident_log(text=None):
    """Split the incident log into active rules, incidents, and open issues.

    The log is the pipeline's long-term memory and its format is stable by
    convention, not by schema: `## Active rules` holds `### Category` groups of
    `- **Label:** statement` bullets, dated `### YYYY-MM-DD: headline` blocks
    hold incidents with `- **Field:** value` bodies, and `## Open issues` holds
    known limitations. Continuation lines belong to whatever bullet opened.
    """
    text = read(INCIDENT_LOG) if text is None else text
    rules, incidents, open_issues = [], [], []
    section = ''
    category = category_id = ''
    rule = incident = issue = None
    field = None

    def close_rule():
        nonlocal rule
        if rule:
            rule['statement'] = ' '.join(rule['statement'].split())
            rules.append(rule)
            rule = None

    def close_incident():
        nonlocal incident, field
        if incident:
            incident['fields'] = {k: ' '.join(v.split()) for k, v in incident['fields'].items()}
            incidents.append(incident)
            incident = None
        field = None

    def close_issue():
        nonlocal issue
        if issue:
            issue['text'] = ' '.join(issue['text'].split())
            open_issues.append(issue)
            issue = None

    for lineno, line in enumerate(text.split('\n'), start=1):
        dated = DATED_ENTRY.match(line)
        if dated:
            close_rule()
            close_incident()
            close_issue()
            incident = {'date': dated.group(1), 'headline': dated.group(2).strip(),
                        'section': section or 'Incident history', 'fields': {}, 'line': lineno}
            continue

        h2 = H2.match(line)
        if h2:
            close_rule()
            close_incident()
            close_issue()
            section = h2.group(1).strip()
            category = category_id = ''
            continue

        h3 = H3.match(line)
        if h3:
            close_rule()
            close_issue()
            if section.startswith('Active rules'):
                category = h3.group(1).strip()
                category_id = slugify(category)
            continue

        bullet = FIELD_BULLET.match(line)
        if bullet and section.startswith('Active rules') and category:
            close_rule()
            label = bullet.group(1).strip()
            rule = {'category': category, 'category_id': category_id, 'label': label,
                    'id': 'R-%s-%s' % (category_id, slugify(label)),
                    'statement': bullet.group(2).strip(), 'line': lineno}
            continue
        if bullet and incident is not None:
            field = bullet.group(1).strip().lower()
            incident['fields'][field] = bullet.group(2).strip()
            continue
        if bullet and section.startswith('Open issues'):
            close_issue()
            issue = {'label': bullet.group(1).strip(), 'text': bullet.group(2).strip(), 'line': lineno}
            continue

        # Continuation: an indented or plain line under whatever bullet is open.
        stripped = line.strip()
        if not stripped or stripped == '---':
            continue
        if rule is not None:
            rule['statement'] += ' ' + stripped
        elif issue is not None:
            issue['text'] += ' ' + stripped
        elif incident is not None and field:
            incident['fields'][field] += ' ' + stripped

    close_rule()
    close_incident()
    close_issue()

    seen = {}
    for r in rules:
        if r['id'] in seen:
            r['duplicate_of'] = seen[r['id']]
        else:
            seen[r['id']] = r['line']
    return {'rules': rules, 'incidents': incidents, 'open_issues': open_issues}


def parse_enforcement():
    """Map rule id to the files that claim to enforce it.

    A claim is a `brain-rule: R-...` marker in a comment. Nothing under brain/
    is scanned: the registry lists rule ids by definition and would otherwise
    report itself as its own enforcement.
    """
    found = defaultdict(list)
    for path in sorted(REPO_ROOT.rglob('*')):
        if not path.is_file():
            continue
        parts = set(path.relative_to(REPO_ROOT).parts)
        if parts & SEARCH_SKIP_DIRS or path.is_relative_to(BRAIN):
            continue
        if path.suffix not in CODE_SUFFIXES | {'.md'} and path.name != 'Makefile':
            continue
        for lineno, line in enumerate(read(path).split('\n'), start=1):
            for match in MARKER.finditer(line):
                found[match.group(1)].append('%s:%d' % (rel(path), lineno))
    return found


def article_status(state, folder):
    """Best supported status for one article folder.

    Only 12 of the article folders carry pipeline-state.json; the rest were
    produced by the earlier system and synced in, so their status has to come
    from the artifacts on disk. Nothing is inferred beyond what a file proves.
    """
    if state.get('stage'):
        return str(state['stage'])
    if (folder / 'delivery-manifest.md').exists():
        return 'delivered'
    if (folder / 'qa-report.md').exists():
        return 'qa-passed'
    if (folder / 'draft.md').exists():
        return 'draft-only'
    return 'empty'


def parse_articles():
    """One row per article folder, from state file plus canonical draft."""
    articles = []
    if not BLOG.is_dir():
        return articles
    for folder in sorted(p for p in BLOG.iterdir() if p.is_dir()):
        state = {}
        state_path = folder / 'pipeline-state.json'
        if state_path.exists():
            try:
                state = json.loads(read(state_path))
            except json.JSONDecodeError:
                state = {}

        draft = None
        for name in ('draft-v2-humanized.md', 'draft-v2.md', 'draft.md'):
            if (folder / name).exists():
                draft = folder / name
                break

        meta = {}
        if draft:
            notes, _ = _mpk.split_notes(read(draft))
            meta = _mpk.parse_notes(notes)

        published = ''
        if draft:
            match = re.search(r'[Pp]ublished:?\s*\*?\*?\s*(\d{4}-\d{2}-\d{2})', read(draft)[:4000])
            if match:
                published = match.group(1)

        flags = state.get('flags', {}) if isinstance(state.get('flags'), dict) else {}
        articles.append({
            'slug': folder.name,
            'title': meta.get('title') or state.get('title') or first_heading(read(draft) if draft else ''),
            'status': article_status(state, folder),
            'draft': rel(draft) if draft else '',
            'published': published,
            'focus_keyword': meta.get('focus_keyword', ''),
            'has_state': bool(state),
            'loop_count': state.get('loop_count', ''),
            'panel': state.get('expert_panel', []),
            'qa': (state.get('qa_summary') or {}).get('recommendation', ''),
            'delivered': (folder / 'delivery-manifest.md').exists(),
            'visuals': sorted(p.name for p in folder.glob('*-visual-*.webp')),
            'reviews': len(list((folder / 'expert-reviews').glob('*.md'))) if (folder / 'expert-reviews').is_dir() else 0,
            'seed_topic': flags.get('seed_topic', ''),
            'artifacts': sorted(p.name for p in folder.iterdir() if p.is_file()),
        })
    return articles


ROADMAP_ROW = re.compile(r'^\|\s*(\d+)\s*\|\s*([^|]+?)\s*\|\s*([^|]*?)\s*\|\s*([^|]*?)\s*\|\s*([^|]*?)\s*\|')
STOPWORDS = {'the', 'a', 'an', 'to', 'for', 'of', 'in', 'and', 'or', 'vs', 'with',
             'is', 'are', 'how', 'what', 'when', 'real', 'estate', 'fractional'}


def topic_tokens(text):
    """Comparable tokens from a topic line, a seed string, a slug, or a keyword.

    Light normalisation only, because the point is to compare human phrasings
    of the same subject: parentheticals dropped, thousands separators removed,
    trailing plural stripped. Digit-suffixed tokens keep every reading, so
    "10k" also counts as 10000 and "401k" also counts as 401, which is what
    lets "$10,000" find `how-to-invest-10k` without turning a 401(k) into a
    number nobody wrote.
    """
    text = re.sub(r'\(.*?\)', ' ', text.lower()).replace(',', '')
    tokens = set()
    for raw in re.findall(r"[a-z0-9$%]+", text):
        token = raw.strip('$%')
        if not token:
            continue
        forms = {token}
        thousands = re.fullmatch(r'(\d+)k', token)
        if thousands:
            forms.add(thousands.group(1))
            forms.add(str(int(thousands.group(1)) * 1000))
        if token.endswith('s') and len(token) > 3:
            forms.add(token[:-1])
            forms.discard(token)
        for form in forms:
            if form in STOPWORDS:
                continue
            if len(form) < 3 and not form.isdigit():
                continue
            tokens.add(form)
    return tokens


def best_match(wanted, candidates):
    """(key, recall) of the candidate covering most of `wanted`.

    Ties go to the tightest candidate, so a topic whose only distinctive word
    is "reit" lands on the article about exactly that and not on the longer
    article that merely contains the word.
    """
    if not wanted:
        return '', 0.0
    ranked = []
    for key, tokens in candidates.items():
        if not tokens:
            continue
        ranked.append((len(wanted & tokens) / len(wanted), -len(tokens), key))
    if not ranked:
        return '', 0.0
    ranked.sort(key=lambda item: (-item[0], -item[1], item[2]))
    recall, _, key = ranked[0]
    return key, recall


def parse_topic_pool(articles=None):
    """ROADMAP Step 2 gap table, matched to the article each gap produced.

    Coverage carries its evidence, because the two available signals are not
    equally strong. A state file that records `seed_topic: ROADMAP Step 2 gap
    #N` is the pipeline reporting its own input, but the number is a position
    in a table that has been renumbered since, so the topic text in that seed
    string is what gets matched and a stale number is reported rather than
    trusted. Everything else is token overlap against a folder name, marked
    with its confidence, and never treated as proof that a gap is closed.
    """
    articles = parse_articles() if articles is None else articles
    text = read(ROADMAP)
    in_step2 = False
    topics = []
    for line in text.split('\n'):
        if line.startswith('## Step 2'):
            in_step2 = True
            continue
        if in_step2 and line.startswith('## '):
            break
        if not in_step2:
            continue
        row = ROADMAP_ROW.match(line)
        if row and row.group(1).isdigit():
            topics.append({'num': int(row.group(1)), 'topic': row.group(2).strip(),
                           'why': row.group(3).strip(), 'kd': row.group(4).strip(),
                           'volume': row.group(5).strip(), 'covered_by': '', 'evidence': ''})

    by_num = {t['num']: t for t in topics}
    rows = {t['num']: topic_tokens(t['topic']) for t in topics}

    for article in articles:
        seed = article.get('seed_topic', '')
        if not seed:
            continue
        claimed = re.search(r'gap #(\d+)', seed)
        seed_text = re.sub(r'^.*?gap #\d+\s*[-:]?\s*', '', seed)
        num, ratio = best_match(topic_tokens(seed_text), rows)
        if not num or ratio < 0.5:
            if claimed and int(claimed.group(1)) in by_num:
                topic = by_num[int(claimed.group(1))]
                topic['covered_by'] = topic['covered_by'] or article['slug']
                topic['evidence'] = 'state file, gap number unverified'
            continue
        topic = by_num[num]
        topic['covered_by'] = article['slug']
        if claimed and int(claimed.group(1)) != num:
            topic['evidence'] = 'state file text, its gap #%s is stale' % claimed.group(1)
        else:
            topic['evidence'] = 'state file'

    article_tokens = {a['slug']: topic_tokens(' '.join([a['slug'], a['focus_keyword'], a['title']]))
                      for a in articles}
    for topic in topics:
        if topic['covered_by']:
            continue
        slug, recall = best_match(topic_tokens(topic['topic']), article_tokens)
        if recall >= 0.6:
            topic['covered_by'] = slug
            topic['evidence'] = 'content match ~%d%%' % round(recall * 100)
    return topics


DOC_GROUPS = [
    ('Operating docs', ['README.md', 'ROADMAP.md', 'CONTRIBUTING.md', 'SECURITY.md', 'CLAUDE.md']),
    ('Pipeline and tooling', ['workflow']),
    ('Checklists and gates', ['checklist']),
    ('Brand', ['brand']),
    ('Competitor intelligence', ['competitors']),
]


def parse_sources():
    """Every operational document with its title, purpose, and size."""
    groups = []
    for name, entries in DOC_GROUPS:
        docs = []
        for entry in entries:
            path = REPO_ROOT / entry
            paths = sorted(path.rglob('*.md')) if path.is_dir() else ([path] if path.exists() else [])
            for doc in paths:
                text = read(doc)
                docs.append({'path': rel(doc), 'title': first_heading(text, doc.stem),
                             'purpose': first_prose(text), 'lines': len(text.split('\n'))})
        if docs:
            groups.append((name, docs))
    return groups


# ---------------------------------------------------------------------------
# generated registries
# ---------------------------------------------------------------------------

def context():
    """Everything the renderers need, parsed once."""
    log = parse_incident_log()
    articles = parse_articles()
    return {
        'rules': log['rules'],
        'incidents': log['incidents'],
        'open_issues': log['open_issues'],
        'articles': articles,
        'topics': parse_topic_pool(articles),
        'sources': parse_sources(),
        'enforcement': parse_enforcement(),
    }


def curated_docs():
    """Hand-written brain files, in reading order, with their one-line purpose."""
    generated = set(GENERATED.keys())
    docs = []
    for path in sorted(BRAIN.rglob('*.md')) if BRAIN.is_dir() else []:
        if rel(path) in generated:
            continue
        text = read(path)
        docs.append({'path': rel(path), 'title': first_heading(text, path.stem),
                     'purpose': first_prose(text)})
    order = {'brain/README.md': 0, 'brain/decisions.md': 1}
    docs.sort(key=lambda d: (order.get(d['path'], 2), d['path']))
    return docs


def render_index(ctx):
    rules, articles, topics = ctx['rules'], ctx['articles'], ctx['topics']
    covered = [t for t in topics if t['covered_by']]
    enforced = [r for r in rules if ctx['enforcement'].get(r['id'])]
    lines = [
        GENERATED_BANNER,
        '',
        '# Brain index',
        '',
        'The map of what this operation knows and where each piece of it lives.',
        'Curated pages hold knowledge that has no other home. Generated registries',
        'are rebuilt from the files that already own the facts, so the index can go',
        'stale but it cannot go wrong: `python3 workflow/brain.py check` fails the',
        'build when it drifts.',
        '',
        '## At a glance',
        '',
        '| Holding | Count |',
        '|---------|-------|',
        '| Active rules | %d |' % len(rules),
        '| Rules with an automated check | %d |' % len(enforced),
        '| Logged incidents | %d |' % len(ctx['incidents']),
        '| Open issues | %d |' % len(ctx['open_issues']),
        '| Article folders | %d |' % len(articles),
        '| Articles with a state file | %d |' % len([a for a in articles if a['has_state']]),
        '| Topic pool entries | %d |' % len(topics),
        '| Topic entries with a matched article | %d |' % len(covered),
        '',
        '## Start here (curated)',
        '',
        '| Page | What it holds |',
        '|------|---------------|',
    ]
    for doc in curated_docs():
        link = doc['path'][len('brain/'):] if doc['path'].startswith('brain/') else '../' + doc['path']
        lines.append('| [%s](%s) | %s |' % (doc['title'], link, cell(doc['purpose'], 150)))
    lines += [
        '',
        '## Generated registries',
        '',
        '| Registry | Built from |',
        '|----------|-----------|',
        '| [Rules](rules.md) | `workflow/incident-log.md` active rules, plus `brain-rule:` markers in code |',
        '| [Incidents](incidents.md) | `workflow/incident-log.md` dated entries and open issues |',
        '| [Articles](articles.md) | `blog/*/pipeline-state.json` and each folder canonical draft |',
        '| [Topics](topics.md) | `ROADMAP.md` Step 2 gap table, matched against published slugs |',
        '',
        '## Where knowledge lives (upstream sources)',
        '',
        'Every row is a source of truth. The brain indexes these; it does not replace them.',
        'Change the source, then rebuild the brain, never the other way round.',
        '',
    ]
    for name, docs in ctx['sources']:
        lines += ['### %s' % name, '', '| Document | Purpose | Lines |', '|----------|---------|-------|']
        for doc in docs:
            lines.append('| [%s](../%s) | %s | %d |' % (doc['path'], doc['path'], cell(doc['purpose'], 110) or cell(doc['title'], 110), doc['lines']))
        lines.append('')
    lines += [
        '## Recall',
        '',
        '```bash',
        'python3 workflow/brain.py search "drive delivery gate"   # ranked, with file:line',
        'python3 workflow/brain.py rules --category tooling        # rules in force',
        'python3 workflow/brain.py stats                           # what the brain holds',
        '```',
    ]
    return emit(lines)


def render_rules(ctx):
    rules, enforcement = ctx['rules'], ctx['enforcement']
    by_category = defaultdict(list)
    for rule in rules:
        by_category[rule['category']].append(rule)

    lines = [
        GENERATED_BANNER,
        '',
        '# Rules registry',
        '',
        'Every rule in force on every run, lifted verbatim from the Active rules',
        'section of [workflow/incident-log.md](../workflow/incident-log.md). Each one',
        'exists because something broke once; the incident that produced it is in',
        '[incidents.md](incidents.md).',
        '',
        'Ids are derived from category and label, so they stay stable while the log',
        'is reordered and change when a rule is renamed. Cite them in reviews, commit',
        'messages, and code comments: a `brain-rule` marker naming a rule id in any',
        'file makes that file show up below as the check that enforces the rule.',
        '',
        '**Enforced by** is the honest column. A rule with no automated check is not a',
        'weaker rule, it is a rule that depends on whoever is running the pipeline',
        'reading this page first.',
        '',
        '| Id | Rule | Enforced by |',
        '|----|------|-------------|',
    ]
    for rule in rules:
        marks = enforcement.get(rule['id'], [])
        lines.append('| `%s` | %s | %s |' % (
            rule['id'], cell(rule['label'], 46),
            ', '.join('`%s`' % m for m in marks) if marks else 'procedural'))
    lines.append('')

    for category in sorted(by_category, key=lambda c: [r['line'] for r in by_category[c]][0]):
        lines += ['## %s' % category, '']
        for rule in by_category[category]:
            marks = enforcement.get(rule['id'], [])
            lines += [
                '### %s' % rule['label'],
                '',
                '- **Id:** `%s`' % rule['id'],
                '- **Rule:** %s' % rule['statement'],
                '- **Source:** [workflow/incident-log.md:%d](../workflow/incident-log.md#L%d)' % (rule['line'], rule['line']),
                '- **Enforced by:** %s' % (', '.join('`%s`' % m for m in marks) if marks
                                           else 'procedural, no automated check'),
                '',
            ]
    return emit(lines)


def describe_years(total, by_year):
    """"20 entries, all from 2026" or "20 entries: 4 in 2025, 16 in 2026"."""
    if not by_year:
        return '%d entries' % total
    if len(by_year) == 1:
        return '%d entries, all from %s' % (total, next(iter(by_year)))
    return '%d entries: %s' % (total, ', '.join('%d in %s' % (n, y) for y, n in sorted(by_year.items())))


def render_incidents(ctx):
    incidents = sorted(ctx['incidents'], key=lambda i: i['date'], reverse=True)
    by_year = Counter(i['date'][:4] for i in incidents)
    lines = [
        GENERATED_BANNER,
        '',
        '# Incident timeline',
        '',
        'What has gone wrong, what it cost, and which rule came out of it. Source is',
        '[workflow/incident-log.md](../workflow/incident-log.md); this page is the index',
        'over it, ordered newest first. Read the source entry before acting on any row.',
        '',
        '%s. Open issues, meaning known limitations nobody has closed yet, are'
        % describe_years(len(incidents), by_year),
        'listed at the bottom.',
        '',
        '| Date | What happened | Stage | Rule it produced | Source |',
        '|------|---------------|-------|------------------|--------|',
    ]
    for incident in incidents:
        fields = incident['fields']
        rule = fields.get('rule') or fields.get('decision') or fields.get('pattern') or ''
        lines.append('| %s | %s | %s | %s | [log:%d](../workflow/incident-log.md#L%d) |' % (
            incident['date'], cell(incident['headline'], 70), cell(fields.get('stage', ''), 28),
            cell(rule, 70) or 'no new rule', incident['line'], incident['line']))
    lines += ['', '## Open issues and known limitations', '']
    if ctx['open_issues']:
        for issue in ctx['open_issues']:
            lines.append('- **%s** %s [(log:%d)](../workflow/incident-log.md#L%d)'
                         % (issue['label'], cell(issue['text'], 400), issue['line'], issue['line']))
    else:
        lines.append('None recorded.')
    return emit(lines)


def render_articles(ctx):
    articles = ctx['articles']
    by_status = Counter(a['status'] for a in articles)
    instrumented = [a for a in articles if a['has_state']]
    lines = [
        GENERATED_BANNER,
        '',
        '# Article registry',
        '',
        'Every article folder under `blog/`, what state it is in, and what it carries.',
        'Status comes from `pipeline-state.json` where one exists. The folders synced in',
        'from the earlier system have no state file, so their status is read off the',
        'artifacts on disk: a delivery manifest means delivered, a QA report means the',
        'gate passed, a lone draft means neither.',
        '',
        '| Status | Folders |',
        '|--------|---------|',
    ]
    for status, count in by_status.most_common():
        lines.append('| %s | %d |' % (status, count))
    lines += [
        '',
        '## All articles',
        '',
        '| Slug | Status | Published | Focus keyword | State | QA | Delivered | Visuals | Reviews |',
        '|------|--------|-----------|---------------|-------|----|-----------|---------|---------|',
    ]
    for a in sorted(articles, key=lambda a: a['slug']):
        lines.append('| [%s](../%s) | %s | %s | %s | %s | %s | %s | %d | %d |' % (
            a['slug'], 'blog/' + a['slug'], a['status'], a['published'] or '.',
            cell(a['focus_keyword'], 40) or '.', 'yes' if a['has_state'] else '.',
            a['qa'] or '.', 'yes' if a['delivered'] else '.', len(a['visuals']), a['reviews']))
    lines += [
        '',
        '## Pipeline-instrumented runs',
        '',
        'Folders with a state file, meaning the run happened in this repo and left a',
        'full audit trail behind it.',
        '',
        '| Slug | Stage | Loops | Expert panel | Seed topic |',
        '|------|-------|-------|--------------|------------|',
    ]
    for a in sorted(instrumented, key=lambda a: a['slug']):
        lines.append('| %s | %s | %s | %s | %s |' % (
            a['slug'], a['status'], a['loop_count'], ', '.join(a['panel']) or '.',
            cell(a['seed_topic'], 52) or '.'))
    return emit(lines)


def render_topics(ctx):
    topics = ctx['topics']
    open_topics = [t for t in topics if not t['covered_by']]
    lines = [
        GENERATED_BANNER,
        '',
        '# Topic pool',
        '',
        'The content gap table from [ROADMAP.md](../ROADMAP.md) Step 2, matched against',
        'what has actually been produced. Two match strengths, and the difference matters:',
        '"state file" means the pipeline itself recorded the gap number it was writing',
        'against, so the match is a fact. "slug match" is token overlap against a folder',
        'name and is a hint for a human to confirm, never proof that a gap is closed.',
        '',
        '%d entries in the pool, %d matched to an article, %d with no match.'
        % (len(topics), len(topics) - len(open_topics), len(open_topics)),
        '',
        '| # | Gap topic | KD | Volume | Matched article | Match evidence |',
        '|---|-----------|----|--------|-----------------|----------------|',
    ]
    for topic in topics:
        lines.append('| %d | %s | %s | %s | %s | %s |' % (
            topic['num'], cell(topic['topic'], 62), cell(topic['kd'], 12) or '.',
            cell(topic['volume'], 16) or '.', topic['covered_by'] or '.',
            topic['evidence'] or '.'))
    lines += ['', '## No matched article', '']
    if open_topics:
        for topic in open_topics:
            lines.append('- **#%d %s** %s' % (topic['num'], topic['topic'], cell(topic['why'], 200)))
    else:
        lines.append('Every pool entry matches an article. Stage -3 should refill the pool.')
    return emit(lines)


GENERATED = {
    'brain/index.md': render_index,
    'brain/rules.md': render_rules,
    'brain/incidents.md': render_incidents,
    'brain/articles.md': render_articles,
    'brain/topics.md': render_topics,
}


# ---------------------------------------------------------------------------
# recall
# ---------------------------------------------------------------------------

HEADING_RE = re.compile(r'^(#{1,6})\s+(.+)$')
# Unicode-aware on purpose: the repo is English but the clone that borrows this
# scorer is Turkish, and an ASCII class silently shreds "köpek" into "k" and
# "pek", which then matches everything.
TOKEN = re.compile(r"[^\W_]+(?:['’_-][^\W_]+)*", re.UNICODE)
COMBINING_DOT = '\u0307'
CHUNK_MAX_LINES = 120


def fold(text):
    """Lowercase for matching.

    Turkish İ lowercases to i plus a combining dot, so "İnanç" and "inanç" would
    otherwise be different tokens. Drop the mark.
    """
    return text.lower().replace(COMBINING_DOT, '')


def scope_of(path):
    parts = Path(path).resolve().relative_to(REPO_ROOT).parts
    if parts[0] == 'brain':
        return 'brain'
    if parts[0] == 'blog':
        return 'blog'
    if Path(path).suffix == '.md':
        return 'ops'
    return 'code'


def corpus_files(scopes):
    for path in sorted(REPO_ROOT.rglob('*')):
        if not path.is_file():
            continue
        parts = path.relative_to(REPO_ROOT).parts
        if set(parts) & SEARCH_SKIP_DIRS:
            continue
        if path.suffix != '.md' and path.suffix not in CODE_SUFFIXES and path.name != 'Makefile':
            continue
        scope = scope_of(path)
        if scope in scopes:
            yield path, scope


def chunks_of(path, scope):
    """Heading-aware chunks, so a hit points at a section, not a whole file."""
    lines = read(path).split('\n')
    chunks, buf, heading, start = [], [], '', 1

    def flush():
        if any(line.strip() for line in buf):
            chunks.append({'path': rel(path), 'scope': scope, 'heading': heading,
                           'line': start, 'lines': list(buf), 'text': '\n'.join(buf)})

    for i, line in enumerate(lines, start=1):
        match = HEADING_RE.match(line) if path.suffix == '.md' else None
        if match or len(buf) >= CHUNK_MAX_LINES:
            flush()
            buf, start = [], i
            if match:
                heading = match.group(2).strip()
        buf.append(line)
    flush()
    return chunks


def index_chunks(chunks):
    """Add the token counts the scorer needs. Any caller can build the chunks."""
    for chunk in chunks:
        chunk['tokens'] = Counter(TOKEN.findall(fold(chunk['text'])))
        chunk['label_tokens'] = set(TOKEN.findall(fold(chunk['heading'] + ' ' + chunk['path'])))
    return chunks


def build_corpus(scopes):
    chunks = []
    for path, scope in corpus_files(scopes):
        chunks.extend(chunks_of(path, scope))
    return index_chunks(chunks)


def search(query, scopes, limit=8, chunks=None):
    """Rank chunks against a query.

    `chunks` lets another corpus borrow this scorer instead of copying it:
    mind.py indexes a store outside the repo and passes it in. Default is the
    repo corpus.
    """
    chunks = build_corpus(scopes) if chunks is None else chunks
    if not chunks:
        return []
    terms = [t for t in TOKEN.findall(fold(query))]
    if not terms:
        return []
    doc_freq = Counter()
    for chunk in chunks:
        for term in set(terms):
            if chunk['tokens'].get(term):
                doc_freq[term] += 1
    total = len(chunks)
    phrase = fold(query).strip()

    scored = []
    for chunk in chunks:
        score = 0.0
        hits = 0
        for term in terms:
            tf = chunk['tokens'].get(term, 0)
            if not tf:
                continue
            hits += 1
            idf = math.log((total + 1) / (doc_freq[term] + 1)) + 1.0
            score += (1 + math.log(tf)) * idf
            if term in chunk['label_tokens']:
                score += 1.5 * idf
        if not hits:
            continue
        score *= (hits / len(terms)) ** 1.5          # reward chunks covering the whole query
        if len(phrase) > 6 and phrase in fold(chunk['text']):
            score += 6.0
        scored.append((score, chunk))

    scored.sort(key=lambda pair: (-pair[0], pair[1]['path'], pair[1]['line']))
    results = []
    for score, chunk in scored[:limit]:
        best_line, best_hits, offset = '', 0, 0
        for i, line in enumerate(chunk['lines']):
            found = sum(1 for term in set(terms) if term in fold(line))
            if found > best_hits:
                best_line, best_hits, offset = line.strip(), found, i
        results.append({'score': round(score, 2), 'path': chunk['path'],
                        'line': chunk['line'] + offset, 'heading': chunk['heading'],
                        'snippet': ' '.join(best_line.split())[:220] or ' '.join(chunk['text'].split())[:220]})
    return results


# ---------------------------------------------------------------------------
# integrity
# ---------------------------------------------------------------------------

MD_LINK = re.compile(r'\[[^\]]*\]\(([^)]+)\)')


def brain_pages():
    pages = [REPO_ROOT / 'CLAUDE.md']
    if BRAIN.is_dir():
        pages += sorted(BRAIN.rglob('*.md'))
    return [p for p in pages if p.exists()]


def check():
    """Every way the brain can be wrong that a machine can see."""
    findings = []
    ctx = context()

    for relpath, renderer in sorted(GENERATED.items()):
        path = REPO_ROOT / relpath
        expected = renderer(ctx)
        if not path.exists():
            findings.append(('FAIL', '%s is missing. Run: python3 workflow/brain.py build' % relpath))
        elif read(path) != expected:
            findings.append(('FAIL', '%s has drifted from its sources. Run: python3 workflow/brain.py build' % relpath))

    seen = {}
    for rule in ctx['rules']:
        if rule['id'] in seen:
            findings.append(('FAIL', 'duplicate rule id %s at incident-log.md:%d and :%d, rename one label'
                             % (rule['id'], seen[rule['id']], rule['line'])))
        seen[rule['id']] = rule['line']
        if not rule['statement']:
            findings.append(('FAIL', 'rule %s has an empty statement at incident-log.md:%d'
                             % (rule['id'], rule['line'])))

    known_rules = set(seen)
    decisions = set(DECISION_REF.findall(read(BRAIN / 'decisions.md')))
    for page in brain_pages():
        text = read(page)
        is_generated = rel(page) in GENERATED
        if is_generated and not text.startswith('<!-- GENERATED'):
            findings.append(('FAIL', '%s lost its generated banner' % rel(page)))
        if not is_generated and text.startswith('<!-- GENERATED'):
            findings.append(('FAIL', '%s carries a generated banner but nothing builds it' % rel(page)))
        for rule_id in set(RULE_REF.findall(text)):
            if rule_id not in known_rules:
                findings.append(('FAIL', '%s cites %s, which is not in the rules registry' % (rel(page), rule_id)))
        for decision_id in set(DECISION_REF.findall(text)):
            if decision_id not in decisions and rel(page) != 'brain/decisions.md':
                findings.append(('FAIL', '%s cites %s, which is not in brain/decisions.md' % (rel(page), decision_id)))
        for target in MD_LINK.findall(text):
            target = target.split('#')[0].split(' ')[0].strip()
            if not target or target.startswith(('http://', 'https://', 'mailto:')):
                continue
            if not (page.parent / target).exists():
                findings.append(('FAIL', '%s links to %s, which does not exist' % (rel(page), target)))

    for rule in ctx['rules']:
        if not ctx['enforcement'].get(rule['id']):
            findings.append(('WARN', 'rule %s has no automated check, it rides on discipline' % rule['id']))

    for article in ctx['articles']:
        if article['status'] == 'empty':
            findings.append(('WARN', 'blog/%s holds no draft' % article['slug']))

    return findings


# ---------------------------------------------------------------------------
# commands
# ---------------------------------------------------------------------------

def cmd_build(args):
    BRAIN.mkdir(parents=True, exist_ok=True)
    ctx = context()
    changed = []
    for relpath, renderer in sorted(GENERATED.items()):
        path = REPO_ROOT / relpath
        expected = renderer(ctx)
        if path.exists() and read(path) == expected:
            print('  unchanged  %s' % relpath)
            continue
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(expected, encoding='utf-8')
        changed.append(relpath)
        print('  wrote      %s' % relpath)
    print('\n%d of %d registries rewritten from source.' % (len(changed), len(GENERATED)))
    return 0


def cmd_check(args):
    findings = check()
    fails = [f for f in findings if f[0] == 'FAIL']
    warns = [f for f in findings if f[0] == 'WARN']
    for level, message in findings:
        if level == 'WARN' and args.quiet:
            continue
        print('  [%s] %s' % (level, message), file=sys.stderr)
    print('\n%d FAIL, %d WARN.' % (len(fails), len(warns)), file=sys.stderr)
    if fails:
        print('The brain no longer matches the repo it describes. Rebuild or fix the '
              'reference, then commit the result.', file=sys.stderr)
        return 1
    if warns and args.strict:
        return 1
    return 0


def cmd_search(args):
    scopes = {'brain', 'ops', 'blog', 'code'} if args.scope == 'all' else {args.scope}
    results = search(' '.join(args.query), scopes, args.limit)
    if not results:
        print('No match for %r in scope %s.' % (' '.join(args.query), args.scope), file=sys.stderr)
        return 1
    for i, hit in enumerate(results, start=1):
        where = '%s:%d' % (hit['path'], hit['line'])
        print('%2d. %-56s %s' % (i, where, ('[%s]' % hit['heading']) if hit['heading'] else ''))
        print('    %s' % hit['snippet'])
    return 0


def cmd_rules(args):
    ctx_rules = parse_incident_log()['rules']
    enforcement = parse_enforcement()
    matches = []
    for rule in ctx_rules:
        if args.category and args.category.lower() not in rule['category_id']:
            continue
        if args.id and args.id.lower() not in rule['id']:
            continue
        if args.grep and args.grep.lower() not in (rule['label'] + ' ' + rule['statement']).lower():
            continue
        matches.append(rule)
    if not matches:
        print('No rule matches that filter.', file=sys.stderr)
        return 1
    for rule in matches:
        marks = enforcement.get(rule['id'], [])
        print('%s  (%s)' % (rule['id'], rule['category']))
        print('  %s: %s' % (rule['label'], rule['statement']))
        print('  source: workflow/incident-log.md:%d   enforced by: %s'
              % (rule['line'], ', '.join(marks) if marks else 'procedural'))
        print('')
    print('%d of %d rules.' % (len(matches), len(ctx_rules)))
    return 0


def cmd_stats(args):
    ctx = context()
    chunks = build_corpus({'brain', 'ops', 'blog', 'code'})
    words = sum(sum(c['tokens'].values()) for c in chunks)
    by_category = Counter(r['category'] for r in ctx['rules'])
    by_status = Counter(a['status'] for a in ctx['articles'])
    enforced = len([r for r in ctx['rules'] if ctx['enforcement'].get(r['id'])])
    incidents = ctx['incidents']

    print('Corpus      %d files, %d chunks, %d words indexed'
          % (len({c['path'] for c in chunks}), len(chunks), words))
    print('Rules       %d active, %d with an automated check' % (len(ctx['rules']), enforced))
    for category, count in by_category.most_common():
        print('              %-24s %d' % (category, count))
    print('Incidents   %d logged, newest %s, %d open issues'
          % (len(incidents), max((i['date'] for i in incidents), default='none'), len(ctx['open_issues'])))
    print('Articles    %d folders' % len(ctx['articles']))
    for status, count in by_status.most_common():
        print('              %-24s %d' % (status, count))
    print('Topics      %d in pool, %d matched to an article'
          % (len(ctx['topics']), len([t for t in ctx['topics'] if t['covered_by']])))
    return 0


def main():
    parser = argparse.ArgumentParser(description='The operation brain: index and recall.')
    sub = parser.add_subparsers(dest='command')

    sub.add_parser('build', help='regenerate the brain registries from their sources').set_defaults(func=cmd_build)

    check_parser = sub.add_parser('check', help='fail when the brain no longer matches the repo')
    check_parser.add_argument('--strict', action='store_true', help='treat warnings as failures')
    check_parser.add_argument('--quiet', action='store_true', help='print failures only')
    check_parser.set_defaults(func=cmd_check)

    search_parser = sub.add_parser('search', help='ranked recall across the repo')
    search_parser.add_argument('query', nargs='+')
    search_parser.add_argument('--scope', default='all', choices=['all', 'brain', 'ops', 'blog', 'code'])
    search_parser.add_argument('--limit', type=int, default=8)
    search_parser.set_defaults(func=cmd_search)

    rules_parser = sub.add_parser('rules', help='print the rules in force')
    rules_parser.add_argument('--category', help='filter by category id, e.g. tooling')
    rules_parser.add_argument('--id', help='filter by rule id fragment')
    rules_parser.add_argument('--grep', help='filter by text in the label or statement')
    rules_parser.set_defaults(func=cmd_rules)

    sub.add_parser('stats', help='what the brain currently holds').set_defaults(func=cmd_stats)

    args = parser.parse_args()
    if not getattr(args, 'func', None):
        parser.print_help()
        return 2
    return args.func(args)


if __name__ == '__main__':
    sys.exit(main())
