#!/usr/bin/env python3
"""
Blog cover generator. Builds 1200x630 covers per brand/cover-image-spec.md.

Design system: flat brand art (cream field, vermillion kicker, ink headline)
with a geometric motif strip along the bottom. All text lives in the spec's
safe zone (x 200 to 1000); the motif strip stays below y 480 so the pixel
check in this script can prove the safe zone is clean. Flat art ships as PNG
per the spec.

Input is a copy deck JSON: a list of
    {"num": 28, "slug": "...", "repo": "<blog folder>",
     "kicker": "...", "lines": ["...", "..."], "motif": "grid"}

For each entry the script writes blog/<repo>/cover-<slug>-1200x630-v2.html,
renders it at 2x with headless Chrome, downscales to exactly 1200x630, and
verifies: exact size, safe zone purity, banned-content rules, weight. A card
crop (the middle 913 px, what the listing actually shows) is saved next to
the PNG as *-card.png for eyeballing; card crops are not uploaded.

Usage:
  python3 workflow/make_cover.py brand/cover-copy-batch2-v2.json
  python3 workflow/make_cover.py deck.json --only how-to-choose-fractional-real-estate-platform
"""
import argparse
import json
import re
import subprocess
import sys
from pathlib import Path

from PIL import Image

REPO_ROOT = Path(__file__).resolve().parent.parent
CHROME = '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'

CREAM = (247, 245, 240)
W, H = 1200, 630
SAFE_X0, SAFE_X1 = 200, 1000
TEXT_BAND_Y0, TEXT_BAND_Y1 = 80, 460   # motif strip starts at 480

BANNED = [
    (re.compile(r'[—–]'), 'dash character'),
    (re.compile(r'\bguarantee[ds]?\b', re.IGNORECASE), 'banned word guarantee(d)'),
    (re.compile(r'Answer capsule|Risk note|Comparison spoke', re.IGNORECASE), 'banned label'),
]

MOTIFS = {
    'grid': '''
      <div style="position:absolute;left:-30px;bottom:-30px;display:flex;gap:14px">
        {cells}
      </div>''',
    'split': '''
      <div style="position:absolute;left:0;bottom:0;width:100%;height:120px;background:var(--blue)"></div>
      <div style="position:absolute;left:0;bottom:104px;width:62%;height:16px;background:var(--vermillion)"></div>
      <div style="position:absolute;right:0;bottom:120px;width:30%;height:10px;background:var(--grey)"></div>''',
    'bars': '''
      <div style="position:absolute;left:0;bottom:0;width:100%;display:flex;align-items:flex-end;gap:18px;padding:0 40px">
        {bars}
      </div>''',
    'stack': '''
      <div style="position:absolute;left:-40px;bottom:0;width:1280px;height:44px;background:var(--grey)"></div>
      <div style="position:absolute;left:60px;bottom:44px;width:1000px;height:40px;background:var(--blue)"></div>
      <div style="position:absolute;left:160px;bottom:84px;width:760px;height:36px;background:var(--vermillion)"></div>''',
    'arc': '''
      <div style="position:absolute;left:50%;bottom:-560px;transform:translateX(-50%);width:1400px;height:700px;border-radius:50%;background:var(--blue)"></div>
      <div style="position:absolute;left:50%;bottom:-620px;transform:translateX(-50%);width:1400px;height:700px;border-radius:50%;background:var(--vermillion)"></div>
      <div style="position:absolute;left:50%;bottom:-680px;transform:translateX(-50%);width:1400px;height:700px;border-radius:50%;background:var(--cream)"></div>''',
    'chevron': '''
      <div style="position:absolute;left:0;bottom:26px;width:100%;display:flex;gap:34px;padding-left:30px">
        {chevrons}
      </div>''',
}


def motif_html(name):
    if name == 'grid':
        fills = ['var(--vermillion)', 'var(--blue)', 'var(--grey)', 'var(--grey)',
                 'var(--blue)', 'var(--vermillion)', 'var(--grey)', 'var(--blue)',
                 'var(--grey)', 'var(--vermillion)', 'var(--blue)', 'var(--grey)']
        cells = ''.join(
            f'<div style="width:88px;height:{h}px;background:{c};align-self:flex-end"></div>'
            for c, h in zip(fills, [64, 96, 48, 80, 56, 104, 72, 48, 88, 64, 96, 56]))
        return MOTIFS['grid'].format(cells=cells)
    if name == 'bars':
        heights = [36, 58, 44, 84, 66, 108, 52, 92, 74, 122, 60, 100, 46, 86]
        colors = ['var(--grey)', 'var(--blue)'] * 6 + ['var(--grey)', 'var(--blue)']
        colors[9] = 'var(--vermillion)'
        bars = ''.join(
            f'<div style="flex:1;height:{h}px;background:{c}"></div>'
            for h, c in zip(heights, colors))
        return MOTIFS['bars'].format(bars=bars)
    if name == 'chevron':
        chevrons = ''
        for i in range(9):
            c = 'var(--vermillion)' if i == 5 else ('var(--blue)' if i % 2 else 'var(--grey)')
            chevrons += (f'<div style="width:96px;height:96px;border-right:20px solid {c};'
                         f'border-bottom:20px solid {c};transform:rotate(-45deg)"></div>')
        return MOTIFS['chevron'].format(chevrons=chevrons)
    return MOTIFS[name]


TEMPLATE = '''<!doctype html>
<!-- Generated by workflow/make_cover.py, do not edit by hand.
     Spec: brand/cover-image-spec.md (safe zone x 200-1000, motif below y 480). -->
<meta charset="utf-8">
<style>
:root{{--cream:#F7F5F0;--ink:#1C1C1C;--vermillion:#FF7141;--blue:#4F8FA3;--grey:#D8D4CC}}
*{{box-sizing:border-box;margin:0;padding:0}}
body{{width:1200px;height:630px;overflow:hidden;position:relative;background:var(--cream);
  font-family:"Söhne","Inter",-apple-system,BlinkMacSystemFont,"Helvetica Neue",Arial,sans-serif;
  -webkit-font-smoothing:antialiased}}
.safe{{position:absolute;left:200px;width:800px;top:{top}px}}
.kicker{{font-size:24px;font-weight:600;letter-spacing:.16em;text-transform:uppercase;
  color:var(--vermillion);margin-bottom:30px}}
h1{{font-size:{fs}px;line-height:1.14;letter-spacing:-.02em;font-weight:700;color:var(--ink)}}
h1 span{{display:block;white-space:nowrap}}
.motif{{position:absolute;left:0;top:480px;width:1200px;height:150px;overflow:visible}}
</style>
<body>
  <div class="safe">
    <div class="kicker">{kicker}</div>
    <h1>{lines}</h1>
  </div>
  <div class="motif">{motif}</div>
</body>
'''


def font_size(lines):
    longest = max(len(l) for l in lines)
    return max(40, min(66, int(800 / (0.56 * longest))))


def build_html(entry):
    lines = entry['lines']
    fs = font_size(lines)
    block_h = 24 + 30 + int(len(lines) * fs * 1.14)
    top = max(110, (460 - block_h) // 2 + 60)
    return TEMPLATE.format(
        top=top, fs=fs,
        kicker=entry['kicker'],
        lines=''.join(f'<span>{l}</span>' for l in lines),
        motif=motif_html(entry['motif']),
    )


def check_banned(entry):
    text = entry['kicker'] + ' ' + ' '.join(entry['lines'])
    return [desc for pat, desc in BANNED if pat.search(text)]


def check_safe_zone(img):
    """Text band rows outside the safe zone must be pure cream."""
    px = img.load()
    bad = 0
    # Scan stops 2 px short of the container boundary: Lanczos ringing puts a
    # 1 px halo (lighter than cream) at x 199 where the kicker's first glyph
    # sits at exactly x 200. The halo is not content; the spec's own slack past
    # the crop line is 57 px, so a 2 px optical guard changes nothing real.
    for y in range(TEXT_BAND_Y0, TEXT_BAND_Y1):
        for x in list(range(0, SAFE_X0 - 2)) + list(range(SAFE_X1 + 2, W)):
            r, g, b = px[x, y][:3]
            # Tolerance 8: Lanczos ringing puts single off-by-6 pixels on the
            # container boundary; genuine ink/motif colours differ by 50+.
            if abs(r - CREAM[0]) > 8 or abs(g - CREAM[1]) > 8 or abs(b - CREAM[2]) > 8:
                bad += 1
    return bad


def render(entry, html_path):
    png_path = html_path.with_suffix('.png')
    r = subprocess.run([
        CHROME, '--headless', '--disable-gpu', '--hide-scrollbars',
        f'--screenshot={png_path}', f'--window-size={W},{H}',
        '--force-device-scale-factor=2', '--virtual-time-budget=3000',
        f'file://{html_path}',
    ], capture_output=True, text=True)
    if not png_path.exists():
        sys.exit(f'Render failed for {html_path.name}:\n{r.stderr[-500:]}')
    img = Image.open(png_path).convert('RGB')
    img = img.resize((W, H), Image.LANCZOS)
    img.save(png_path, optimize=True)
    card = img.crop((143, 0, 1057, H))
    card.save(png_path.with_name(png_path.stem + '-card.png'), optimize=True)
    return png_path, img


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('deck', help='Copy deck JSON')
    ap.add_argument('--only', action='append', help='Limit to slug(s)')
    args = ap.parse_args()

    deck = json.loads(Path(args.deck).read_text())
    if args.only:
        deck = [d for d in deck if d['slug'] in args.only]

    failures = 0
    for entry in deck:
        problems = check_banned(entry)
        for line in entry['lines']:
            if len(line) > 26:
                problems.append(f'line over 26 chars: "{line}" ({len(line)})')
        if len(entry['kicker']) > 28:
            problems.append(f'kicker over 28 chars ({len(entry["kicker"])})')
        if problems:
            print(f'FAIL {entry["slug"]}: {problems}')
            failures += 1
            continue

        folder = REPO_ROOT / 'blog' / entry['repo']
        html_path = folder / f'cover-{entry["slug"]}-1200x630-v2.html'
        html_path.write_text(build_html(entry))
        png_path, img = render(entry, html_path)

        checks = []
        if img.size != (W, H):
            checks.append(f'size {img.size}')
        leak = check_safe_zone(img)
        if leak:
            checks.append(f'{leak} non-cream pixels outside safe zone in text band')
        kb = png_path.stat().st_size / 1024
        if kb > 150:
            checks.append(f'{kb:.0f} KB over 150')

        status = 'OK  ' if not checks else 'FAIL'
        if checks:
            failures += 1
        print(f'{status} {entry["num"]:>2} {entry["slug"]:<46} {kb:6.1f} KB  {checks or ""}')

    return 1 if failures else 0


if __name__ == '__main__':
    sys.exit(main())
